export const GET_COMPLAINS = 'GET_COMPLAINS';
export const GET_COMPLAINS_SUCCESS = 'GET_COMPLAINS_SUCCESS';
export const GET_COMPLAINS_FAILURE = 'GET_COMPLAINS_FAILURE';

export const DELETE_COMPLAIN = 'DELETE_COMPLAIN';
export const DELETE_COMPLAIN_SUCCESS = 'DELETE_COMPLAIN_SUCCESS';
export const DELETE_COMPLAIN_FAILURE = 'DELETE_COMPLAIN_FAILURE';

export const GET_COMPLAINS_TITLE = 'GET_COMPLAINS_TITLE';
export const GET_COMPLAINS_TITLE_SUCCESS = 'GET_COMPLAINS_TITLE_SUCCESS';
export const GET_COMPLAINS_TITLE_FAILURE = 'GET_COMPLAINS_TITLE_FAILURE';

export const UPDATE_COMPLAIN = 'UPDATE_COMPLAIN';
export const UPDATE_COMPLAIN_SUCCESS = 'UPDATE_COMPLAIN_SUCCESS';
export const UPDATE_COMPLAIN_FAILURE = 'UPDATE_COMPLAIN_FAILURE';

export const CREATE_COMPLAIN = 'CREATE_COMPLAIN';
export const CREATE_COMPLAIN_SUCCESS = 'CREATE_COMPLAIN_SUCCESS';
export const CREATE_COMPLAIN_FAILURE = 'CREATE_COMPLAIN_FAILURE';

export const GET_BY_COMPLAIN_ID = 'GET_BY_COMPLAIN_ID';

export const CREATE_COMPLAINT_TYPE = 'CREATE_COMPLAINT_TYPE';
export const CREATE_COMPLAINT_TYPE_SUCCESS = 'CREATE_COMPLAINT_TYPE_SUCCESS';
export const CREATE_COMPLAINT_TYPE_FAILURE = 'CREATE_COMPLAINT_TYPE_FAILURE';

export const UPDATE_COMPLAINT_TYPE = 'UPDATE_COMPLAINT_TYPE';
export const UPDATE_COMPLAINT_TYPE_SUCCESS = 'UPDATE_COMPLAINT_TYPE_SUCCESS';
export const UPDATE_COMPLAINT_TYPE_FAILURE = 'UPDATE_COMPLAINT_TYPE_FAILURE';

export const DELETE_COMPLAINT_TYPE = 'DELETE_COMPLAINT_TYPE';
export const DELETE_COMPLAINT_TYPE_SUCCESS = 'DELETE_COMPLAINT_TYPE_SUCCESS';
export const DELETE_COMPLAINT_TYPE_FAILURE = 'DELETE_COMPLAINT_TYPE_FAILURE';