export const GET_COMPLAINS = 'GET_COMPLAINS';
export const GET_COMPLAINS_SUCCESS = 'GET_COMPLAINS_SUCCESS';
export const GET_COMPLAINS_FAILURE = 'GET_COMPLAINS_FAILURE';

export const DELETE_COMPLAIN = 'DELETE_COMPLAIN';
export const DELETE_COMPLAIN_SUCCESS = 'DELETE_COMPLAIN_SUCCESS';
export const DELETE_COMPLAIN_FAILURE = 'DELETE_COMPLAIN_FAILURE';

export const GET_COMPLAINS_TITLE = 'GET_COMPLAINS_TITLE';
export const GET_COMPLAINS_TITLE_SUCCESS = 'GET_COMPLAINS_TITLE_SUCCESS';
export const GET_COMPLAINS_TITLE_FAILURE = 'GET_COMPLAINS_TITLE_FAILURE';

export const UPDATE_COMPLAIN = 'UPDATE_COMPLAIN';
export const UPDATE_COMPLAIN_SUCCESS = 'UPDATE_COMPLAIN_SUCCESS';
export const UPDATE_COMPLAIN_FAILURE = 'UPDATE_COMPLAIN_FAILURE';