export const ANSWER_CLAIM_COMPLAINT = 'ANSWER_CLAIM_COMPLAINT';
export const ANSWER_CLAIM_COMPLAINT_SUCCESS = 'ANSWER_CLAIM_COMPLAINT_SUCCESS';
export const ANSWER_CLAIM_COMPLAINT_FAILURE = 'ANSWER_CLAIM_COMPLAINT_FAILURE';