export const ANSWER_CLAIM_COMPLAINT = "ANSWER_CLAIM_COMPLAINT";
export const ANSWER_CLAIM_COMPLAINT_SUCCESS = "ANSWER_CLAIM_COMPLAINT_SUCCESS";
export const ANSWER_CLAIM_COMPLAINT_FAILURE = "ANSWER_CLAIM_COMPLAINT_FAILURE";

export const GET_ANSWERS = "GET_ANSWERS";
export const GET_ANSWERS_SUCCESS = "GET_ANSWERS_SUCCESS";
export const GET_ANSWERS_FAILURE = "GET_ANSWERS_FAILURE";

export const GET_CLAIMS_ANSWER = "GET_CLAIMS_ANSWER";
export const GET_CLAIMS_ANSWER_SUCCESS = "GET_CLAIMS_ANSWER_SUCCESS";
export const GET_CLAIMS_ANSWER_FAILURE = "GET_CLAIMS_ANSWER_FAILURE";

export const GET_COMPLAINTS_ANSWER = "GET_COMPLAINTS_ANSWER";
export const GET_COMPLAINTS_ANSWER_SUCCESS = "GET_COMPLAINTS_ANSWER_SUCCESS";
export const GET_COMPLAINTS_ANSWER_FAILURE = "GET_COMPLAINTS_ANSWER_FAILURE";

export const UPDATE_ANSWER = "UPDATE_ANSWER";
export const UPDATE_ANSWER_SUCCESS = "UPDATE_ANSWER_SUCCESS";
export const UPDATE_ANSWER_FAILURE = "UPDATE_ANSWER_FAILURE";
