export const AUTH_USER = "AUTH_USER";
export const AUTH_USER_SUCCESS = "AUTH_USER_SUCCESS";
export const AUTH_USER_FAILURE = "AUTH_USER_FAILURE";

export const CREATE_USER = "CREATE_USER";
export const CREATE_USER_SUCCESS = "CREATE_USER_SUCCESS";
export const CREATE_USER_FAILURE = "CREATE_USER_FAILURE";

export const RESET_PROPERTIES = "RESET_PROPERTIES";

export const GET_EMPLOYESS = "GET_EMPLOYESS";
export const GET_EMPLOYESS_SUCCESS = "GET_EMPLOYESS_SUCCESS";
export const GET_EMPLOYESS_FAILURE = "GET_EMPLOYESS_FAILURE";

export const LOGOUT_USER = "LOGOUT_USER";
