export const GET_CLAIMS = 'GET_CLAIMS';
export const GET_CLAIMS_SUCCESS = 'GET_CLAIMS_SUCCESS';
export const GET_CLAIMS_FAILURE = 'GET_CLAIMS_FAILURE';

export const DELETE_CLAIM = 'DELETE_CLAIM';
export const DELETE_CLAIM_SUCCESS = 'DELETE_CLAIM_SUCCESS';
export const DELETE_CLAIM_FAILURE = 'DELETE_CLAIM_FAILURE';

export const GET_CLAIMS_TITLE = 'GET_CLAIMS_TITLE';
export const GET_CLAIMS_TITLE_SUCCESS = 'GET_CLAIMS_TITLE_SUCCESS';
export const GET_CLAIMS_TITLE_FAILURE = 'GET_CLAIMS_TITLE_FAILURE';

export const UPDATE_CLAIM = 'UPDATE_CLAIM';
export const UPDATE_CLAIM_SUCCESS = 'UPDATE_CLAIM_SUCCESS';
export const UPDATE_CLAIM_FAILURE = 'UPDATE_CLAIM_FAILURE';

export const CREATE_CLAIM = 'CREATE_CLAIM';
export const CREATE_CLAIM_SUCCESS = 'CREATE_CLAIM_SUCCESS';
export const CREATE_CLAIM_FAILURE = 'CREATE_CLAIM_FAILURE';

export const GET_BY_CLAIM_ID = 'GET_BY_CLAIM_ID';

export const CREATE_CLAIM_TYPE = 'CREATE_CLAIM_TYPE';
export const CREATE_CLAIM_TYPE_SUCCESS = 'CREATE_CLAIM_TYPE_SUCCESS';
export const CREATE_CLAIM_TYPE_FAILURE = 'CREATE_CLAIM_TYPE_FAILURE';

export const UPDATE_CLAIM_TYPE = 'UPDATE_CLAIM_TYPE';
export const UPDATE_CLAIM_TYPE_SUCCESS = 'UPDATE_CLAIM_TYPE_SUCCESS';
export const UPDATE_CLAIM_TYPE_FAILURE = 'UPDATE_CLAIM_TYPE_FAILURE';

export const DELETE_CLAIM_TYPE = 'DELETE_CLAIM_TYPE';
export const DELETE_CLAIM_TYPE_SUCCESS = 'DELETE_CLAIM_TYPE_SUCCESS';
export const DELETE_CLAIM_TYPE_FAILURE = 'DELETE_CLAIM_TYPE_FAILURE';